from .main_menu import menu
from .catalog_menu import catalog
from .kfc_menu import kfc_menu_keyboard
from .mac_menu import mac_menu_keyboard
from .vpn_menu import vpn_menu_keyboard
from .games_menu import games_menu_keyboard
from .balance_menu import balance_menu_keyboard
from .yandex_menu import yandex_menu_keyboard
from .count_pay import count_pay_key
from .payment_method import payment_method_keyboard
